exports.lists = [
  {2493: {stageStatus: 'Curently In', metaStage: 'Application', rollupStage: 'Contract Signed, pre-Program Start', stage: 'Contract Signed, pre-Program Start'}},
  {2494: {stageStatus: 'Curently In', metaStage: 'Program Start', rollupStage: 'Program Start prior to Commitment', stage: 'Program Start prior to Commitment'}},
  {2495: {stageStatus: 'Curently In', metaStage: 'Program', rollupStage: 'Commitment - Phase 4 End', stage: 'Crossed Commitment to End Phase 1'}},
  {2496: {stageStatus: 'Curently In', metaStage: 'Program', rollupStage: 'Commitment - Phase 4 End', stage: 'Phase 2 Start-End'}},
  {2497: {stageStatus: 'Curently In', metaStage: 'Program', rollupStage: 'Commitment - Phase 4 End', stage: 'Phase 3 Start-End'}},
  {2498: {stageStatus: 'Curently In', metaStage: 'Program', rollupStage: 'Commitment - Phase 4 End', stage: 'Phase 4 Start-End'}},
  {2499: {stageStatus: 'Curently In', metaStage: 'Job Search', rollupStage: 'Phase 5 Start-End', stage: 'Phase 5 Start-End'}},
  {2501: {stageStatus: 'Curently In', metaStage: 'Job Search', rollupStage: 'Graduation to Job Start', stage: 'Graduation to Job Start'}},
  {2502: {stageStatus: 'Curently In', metaStage: 'Job Search', rollupStage: 'Job Accepted, prior to first ISA Payment', stage: 'Job Accepted, prior to first ISA Payment'}},
  {2512: {stageStatus: 'Curently In', metaStage: 'ISA Payment', rollupStage: 'ISA in Payment', stage: '1st ISA Payment-5th ISA Payment'}},
  {2513: {stageStatus: 'Curently In', metaStage: 'ISA Payment', rollupStage: 'ISA in Payment', stage: '6th ISA Payment-35th ISA Payment'}},
  {2514: {stageStatus: 'Curently In', metaStage: 'ISA Paid', rollupStage: 'ISA Paid', stage: 'Final ISA Payment Made'}},
  {2591: {stageStatus: 'Out During Stage', metaStage: 'Application', rollupStage: 'Contract Signed, pre-Program Start', stage: 'Contract Signed, pre-Program Start'}},
  {2592: {stageStatus: 'Out During Stage', metaStage: 'Program', rollupStage: 'Commitment - Phase 4 End', stage: 'Crossed Commitment to End Phase 1'}},
  {2593: {stageStatus: 'Out During Stage', metaStage: 'Program', rollupStage: 'Commitment - Phase 4 End', stage: 'Phase 2 Start-End'}},
  {2594: {stageStatus: 'Out During Stage', metaStage: 'Program', rollupStage: 'Commitment - Phase 4 End', stage: 'Phase 3 Start-End'}},
  {2595: {stageStatus: 'Out During Stage', metaStage: 'Program', rollupStage: 'Commitment - Phase 4 End', stage: 'Phase 4 Start-End'}},
]

exports.properties = [
  'exit_phase',
  'exit_type',
  'firstname',
  'lastname',
  'email',
  'enrollee_start_date',
  'resignation_date',
  'phase',
  'dob_mm_dd_yyyy_',
  'income_level',
  'race_ethnicity',
  'cancellation_date',
  'current_employment_status',
  'highest_degree_earned',
  'gender',
  'createdate',
  'ps_inactive_type',
  'has_llf',
  'has_pif',
  'llf_amount_eligible',
  'llf_amount_accepted',
  'llf_amount_received',
  'llf_payment_count',
  'llf_income_percent',
  'llf_date_signed',
  'llf_status',
  'pif_amount_eligible',
  'pif_amount_accepted',
  'pif_amount_received',
  'pif_payment_count',
  'pif_income_percent',
  'pif_date_signed',
  'pif_status',
  'has_received_llf_financing',
  'learner_s_starting_salary',
  'have_you_accepted_a_job_offer',
  'isa_data',
  'total_payments_received',
  'isa_payments_past_due'
]
