'use strict'
const moment = require('moment')
const _ = require('lodash')

exports.fields = [
  'hubspot_canonical_vid',
  'email',
  'firstname',
  'lastname',
  'dob_mm_dd_yyyy_',
  'gender',
  'race',
  'two_or_more_races',
  'highest_degree_earned',
  'income_level',
  'current_employment_status',
  'createdate',
  'enrollee_start_date',
  'cancellation_date',
  'phase',
  'resignation_date',
  'exit_type',
  'exit_phase',
  'ps_inactive_type',
  'stageStatus',
  'metaStage',
  'rollupStage',
  'stage',
  'has_llf',
  'llf_amount_eligible',
  'llf_amount_accepted',
  'llf_amount_received',
  'llf_payment_count',
  'llf_income_percent',
  'llf_date_signed',
  'llf_monthly_payment_amount',
  'llf_first_payment_due_date',
  'llf_status',
  'has_pif',
  'pif_amount_eligible',
  'pif_amount_accepted',
  'pif_amount_received',
  'pif_payment_count',
  'pif_income_percent',
  'pif_date_signed',
  'pif_monthly_payment_amount',
  'pif_first_payment_due_date',
  'pif_status',
  'learner_s_starting_salary',
  'learner_reported_salary',
  'have_you_accepted_a_job_offer',
  'has_received_llf_financing',
  'total_payments_received',
  'isa_payments_past_due',
  'job_title',
  'job_start_date',
  'weekly_part_time_hours'
]

exports.numFields = [
  'llf_amount_eligible',
  'llf_amount_accepted',
  'llf_amount_received',
  'llf_payment_count',
  'llf_income_percent',
  'llf_monthly_payment_amount',
  'pif_amount_eligible',
  'pif_amount_accepted',
  'pif_amount_received',
  'pif_payment_count',
  'pif_income_percent',
  'pif_monthly_payment_amount',
  'learner_s_starting_salary',
  'learner_reported_salary',
  'total_payments_received',
  'weekly_part_time_hours'
]

exports.dateFields = [
  'dob_mm_dd_yyyy_',
  'createdate',
  'enrollee_start_date',
  'cancellation_date',
  'resignation_date',
  'llf_date_signed',
  'llf_first_payment_due_date',
  'pif_date_signed',
  'pif_first_payment_due_date',
  'job_start_date'
]
